### ISSUE TITLE
运行遇到错误  抓取的是esj小说

### ISSUE THREAD

**Issue by alsyxi** [ilusrdbb/lightnovel-pydownloader#1]
2023-10-18 10:57:59,470 - 登录成功！
2023-10-18 10:58:02,674 - Task exception was never retrieved
future: <Task finished name='Task-4' coro=<async_build_book() done, defined at service\book.py:70> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "service\book.py", line 98, in async_build_book
  File "service\book.py", line 50, in __init__
  File "zhconv\zhconv.py", line 255, in convert
  File "zhconv\zhconv.py", line 90, in getdict
  File "zhconv\zhconv.py", line 76, in loaddict
  File "zhconv\zhconv.py", line 34, in <lambda>
  File "pkg_resources\__init__.py", line 1136, in resource_stream
  File "pkg_resources\__init__.py", line 1385, in get_resource_stream
  File "pkg_resources\__init__.py", line 1388, in get_resource_string
  File "pkg_resources\__init__.py", line 1555, in _get
  File "PyInstaller\loader\pyimod02_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hansh\\AppData\\Local\\Temp\\_MEI163202\\zhconv\\zhcdict.json'

**Comment by ilusrdbb** [comment]
第三方包zhconv由于引进了json导致使用默认spec打包exe出现问题，现已解决

**Comment by alsyxi** [comment]
![image](https://github.com/ilusrdbb/lightnovel-pydownloader/assets/148303380/9e39b2ac-9fcb-4225-af8c-5949d40a4b6b)
![image](https://github.com/ilusrdbb/lightnovel-pydownloader/assets/148303380/1fe7e835-784a-4be9-aa15-e367a90adda3)
大佬再帮帮我   下载了新的安装包  抓取的结果存在问题  再book那个文件夹内的txt内容是链接不是文本

**Comment by ilusrdbb** [comment]
请确认此地址配置是否被修改过
![image](https://github.com/ilusrdbb/lightnovel-pydownloader/assets/26247398/88c9e775-40d4-45d1-a9c0-69d725b77ff5)

**Comment by ilusrdbb** [comment]
外链的判断已放宽，目前不限于域名后缀是cc还是me

**Comment by alsyxi** [comment]
感谢大佬  已成功爬取  弄成epub看得就舒服多了
